os: osx
osx_image: xcode11.3.1
language: swift
script: xcodebuild clean build test -project FlightSchedule/FlightScheduler.xcodeproj -scheme FlightScheduler -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro Max" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
